### ISSUE TITLE
Provide commonjs version

### ISSUE THREAD

**Issue by just-boris** [deepsweet/mnth#2]
Thank you for the wonderful library, it is a really handy utility!

However, currently it is hard to integrate this into an project, because it ships only es-modules version. In particular, it causes problems with Jest, that [does not have es-modules support](https://github.com/facebook/jest/issues/4842). (esm also [does not work](https://github.com/standard-things/esm/issues/706)).

Currently I have to work it around via running Babel for node_modules (recommended here https://github.com/standard-things/esm/issues/706#issuecomment-489620405), which has its own set of problems. 

Most of the npm-modules, still ship commonjs version, so `mnth` is one of the few causing this issue.

**Comment by deepsweet** [comment]
I've removed ESM loader from all my libs recently and just forgot about `mnth`. Will be definitely fixed.

**Comment by deepsweet** [comment]
Landed with v0.1.2

**Comment by just-boris** [comment]
Thank you!
